### ISSUE TITLE
Validating nested JSON

### ISSUE THREAD

**Issue by Lewiscowles1986** [brightcove/brine#115]
Going by 

https://github.com/brightcove/brine/blob/f8a65cdae033cf2fbe062169fcf6f8663f243bed/features/assertions/is_including.feature

I was expecting to be able to submit a JSON body to an endpoint which returns 201 and a JSON body

```
Feature: Creating people resources.

  Scenario: A request for creating a resource with a known valid value.
    When the request body is assigned:
      """
      {"name":"Jet Li",
      "timezone":"GMT",
      "skills":"Being the one, killing selves in the multiverse"}
      """
    And a POST is sent to `/people`
    And the request header `Content-Type` is assigned `application/json`
    Then the value of the response status is equal to `201`
    And the value of the response body is including:
      """
      "Jet Li"
      """

```

I've also tried `response body as JSON is including:`

and 

```
"""
{"name":"Jet Li"}
"""
```

and 

```
"""
{"data":{"name":"Jet Li"}}
"""
```

when I test using CURL this works

```
curl -X POST --data '{"name":"Jet Li","timezone":"GMT","skills":"Being the one, killing selves in the multiverse"}' -H "Content-Type: application/json" http://localhost:8080/people
```

I receive

```
{
  "data": {
    "email": null,
    "external_id": null,
    "global_admin": false,
    "name": "Jet Li",
    "pk": "ddd1798c-da09-4538-b671-e9b21744d4ed",
    "receive_marketing": false,
    "skills": [
      "Being the one",
      "killing selves in the multiverse"
    ],
    "timezone": "GMT"
  },
  "links": [
    {
      "Href": "/people/ddd1798c-da09-4538-b671-e9b21744d4ed/time",
      "Rel": "time",
      "Type": "GET"
    },
    {
      "Href": "/people",
      "Rel": "listing",
      "Type": "GET"
    }
  ]
}
```

I do get the status code I would like. It's the testing that the JSON that comes back contains the fields sent in (preferably checking they exist under "data" sub-object and are JSON)

**Comment by mwhipple** [comment]
Partial/include matching doesn't work recursively, so you need to select the child that is being tested. Something like:
```
Then the request body child `data` is including:
  """
  {"name": "Jet Li"}
  """
```

Where that JSON could be any subset of data (but each must be full matches). I'll look at getting this case documented more explicitly.  Let me know if you have any further questions!

**Comment by Lewiscowles1986** [comment]
Thank you, I literally came to post that. Sorry for bothering you

**Comment by Lewiscowles1986** [comment]
Would you like a PR for documentation?

**Comment by mwhipple** [comment]
That would be great.
