### ISSUE TITLE
Publish docker image

### ISSUE THREAD

**Issue by mwhipple** [brightcove/brine#186]

**Comment by mwhipple** [comment]
I need to reboot my laptop with a kernel that has been configured to support docker, so I'll come back to this one after I do that.

**Comment by Lewiscowles1986** [comment]
Still interested in this?

**Comment by mwhipple** [comment]
There is definitely still interest, if you wanted to grab it that would be great: otherwise I can probably take care of it next week during the holiday break.

Sorry for the delayed response, I'm no longer part of this org so I need to figure out some of the issues around access :)

**Comment by Lewiscowles1986** [comment]
Sorry to hear that @mwhipple hopefully onwards and upwards. Sounded like nice people when I chatted to them 1-2 years back. I found this and JSONPath so swings and roundabouts for me.

What did you need the Dockerfile to do. Is it for deploying, testing, spelunking?

**Comment by mwhipple** [comment]
I missed your last question until now (I'd guess it was part of an edit that wasn't in the email).

The idea behind the image would be that it would include all of the dependencies so that any set of tests which does not pull new dependencies in could easily bind mount the features directory into a container: so an entire build configuration could be little more than `docker run --rm ${MOUNT_FEATURES} ${RUN_TESTS}` (most likely with another output mount for reports)

The Dockerfile itself could set that up by extending one of the existing base ruby images (and theoretically other runtimes longer term) and add the instructions to fetch the dependencies...nothing too interesting but enough to help with simple suites.

The general motivation is that in CI especially something like this is likely to swing between the two extremes of either being tied too closely to a build agent (which leads to per-agent maintenance burden) or to rely on overly ephemeral containerization which invites builds where a large chunk of the time is spent repeatedly fetching the same dependencies.

I can grab this later this week but will likely jump on #199 first.

**Comment by mwhipple** [comment]
I'm starting this now so should have something by Monday. I'm currently planning on just publishing to my Docker Hub account since I don't think the Brightcove one is readily usable and I'm no longer in a position to get that wired.

If anyone within Brightcove wants to take that on then adding encrypted credentials to the Travis config should allow the image to published through CI, #183 is expanded to cover the additional artifact.

**Comment by mwhipple** [comment]
looks like I need to pass the systemd.unified_cgroup_hierarchy=0 boot parameter for docker to fully work on the system I'm using which may push this into next week depending on how much free time I can scrounge up over the weekend.

**Comment by mwhipple** [comment]
PR is up, I'll harass/brine/fork as needed if the PRs languish through next week.
