### ISSUE TITLE
Support for eventual tests

### ISSUE THREAD

**Issue by mwhipple** [brightcove/brine#27]
Ideally some kind of bracketing to reuse existing steps, something like

```gherkin
When a delay is expected
And a GET is sent to `/`
Then `response.status` equals `200`
And this is eventually satisfied
```

The last line could have parameterized versions where either a time or some kind of named duration can be specified.

The current idea for behavior would be that the first line changes the behavior of step registration so that the logic is collected into a thunk, and then the last line executes that thunk with the appropriate timeout.

**Comment by mwhipple** [comment]
This one has been simmering for a long time awaiting a decent approach to be plugged into the language but now upon revisiting it I think I have an initial idea around the concept of "actions" (though an alternate name would work)

example:
```gherkin
When actions are defined such that
  When a GET is sent to `/`
  Then the value of the response status is equal to `200`
Then the actions are successful within a `short` period
```

Where short is a parameter which could either be specified in code or through an environment variable convention (`BRINE_PERIOD_short`)

Internally this would be implemented by having all steps pass through a function such as:
```ruby
perform {
  # do stuff
}
```
which would normally immediately evaluate the passed block, but in the case of defining the actions they will be collected as thunks for deferred evaluation which will then be triggered by the `the actions  ...` step.

This overall structure could also be used to drive a bunch of other logic such as iteration, and the idea of naming the bundled actions could be done easily...but most of that would be resisted without reason (maybe with some docs to allow someone to plug into it for whatever nefarious purposes they can think of).

**Comment by mwhipple** [comment]
@tjaneczko What do you think of ^^

**Comment by tjaneczko** [comment]
I think this could be helpful, although it might not handle negative tests (i.e. ensuring something did not change within a given timeframe)

**Comment by mwhipple** [comment]
Good point...the last statement could support being negated also in a way that is consistent with the other steps:

```
Then the actions are [not] successful within a `short` period
```

**Comment by mwhipple** [comment]
Solved with provided "actions"
